---
name: CI/CD

on :
  push :
    branches: main
jobs:
  greet:
    runs-on: ubantu-latest
    steps:
     - name: Hello to everyone
       run: echo "doing well"
    
  nginx:
     runs-on: ubantu-latest
     steps:
       - name: good night
         run: echo "Hello"
