name: cicd

on:
  push:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: hello everyone
        run: echo "good afternoon"
      - name: hope you are well
        run: echo "i am very well"
  done:
    runs-on: ubuntu-latest
    steps:
      - name: docker version
        run: docker --version
